/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pk_ndk_Holder */

#ifndef _Included_pk_ndk_Holder
#define _Included_pk_ndk_Holder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pk_ndk_Holder
 * Method:    print
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pk_ndk_Holder_print
  (JNIEnv *, jobject);

/*
 * Class:     pk_ndk_Holder
 * Method:    plus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_pk_ndk_Holder_plus
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     pk_ndk_Holder
 * Method:    testCallJava
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_pk_ndk_Holder_testCallJava
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
